Meowhal/osu-ahr

config/default.json, package-lock.json, package.json, src/dummies/DummyLobbyPlugin.ts, src/plugins/AutoHostSelector.ts, src/plugins/AutoStartTimer.ts, src/plugins/HistoryLoader.ts, src/plugins/HostSkipper.ts, src/plugins/InOutLogger.ts, src/plugins/LobbyKeeper.ts, src/plugins/LobbyPlugin.ts, src/plugins/LobbyTerminator.ts, src/plugins/MapChecker.ts, src/plugins/MapRecaster.ts, src/plugins/MatchAborter.ts, src/plugins/MatchStarter.ts, src/plugins/ProfileFecher.ts, src/plugins/WordCounter.ts
=> discord統合前準備

README.md
=> Discord Intergration English translations

README.md
Thank you for the special thanks! ❤️
=> Update username to Metacinnabar

src/discord/DiscordBot.ts, src/plugins/AutoHostSelector.ts, src/plugins/MapChecker.ts, src/web/statics/index.html
- Fix Typo
- Add Game Mode on Reject Unfit Map to Revert Current Game Mode
- Add Verbosity to Map Checker Violation Message, (Example see below)
=> Fix Typo and Add Verbosity to Map Checker

src/plugins/MapChecker.ts, src/webapi/BeatmapRepository.ts
~~Add map availability checker to warn player if there is availability problem in direct download map (disabled download or portion beatmap missing).~~
Reject map if beatmap download link isn't available or portion of it missing.
Example of beatmap that has disabled download or portion of beatmap missing
=> Add Reject Map Validation in Map Checker

README.md
This capitalizes some letters and words in the documentation in accordance and respect on how the documentation is made, to be consistent with other keywords found in the documentation.
=> docs: apply proper capitalizations

src/cli/OahrBase.ts, src/cli/OahrCli.ts, src/cli/OahrHeadless.ts, src/cli/index.ts
=> refactor(cli): improve texts and error messages

src/discord/BotCommand.ts, src/discord/DiscordAppender.ts, src/discord/DiscordBot.ts, src/discord/OahrDiscord.ts, src/discord/index.ts
=> refactor(discord): improve texts and error messages

src/plugins/AfkKicker.ts
Addresses remaining inconsistencies on `AfkKicker` plugin for #90
=> refactor(plugins#AfkKicker): inconsistencies

src/cli/OahrBase.ts, src/cli/OahrCli.ts
Addresses remaining inconsistencies in the `cli` directory for #90
=> refactor(cli): inconsistencies

src/plugins/LobbyTerminator.ts
#90 for `LobbyTerminator` plugin.
=> refactor(plugins#LobbyTerminator): improve texts and error messages

src/plugins/MapChecker.ts
=> refactor(plugins#MapChecker): improve texts and error messages

src/plugins/MatchAborter.ts
#90 for `MatchAborter` plugin.
=> refactor(plugins#MatchAborter): improve texts and error messages

src/plugins/MatchStarter.ts
#90 for `MatchStarter` plugin.
=> refactor(plugins#MatchStarter): improve texts and error messages

src/plugins/ProfileFecher.ts
#90 for `ProfileFecher` plugin.
=> refactor(plugins#ProfileFecher): improve texts and error messages

src/plugins/MiscLoader.ts
=> refactor(plugins#MiscLoader): improve texts and error messages

src/plugins/WordCounter.ts
=> refactor(plugins#WordCounter): improve texts and error messages

src/webapi/HistoryRepository.ts, src/webapi/WebApiClient.ts
=> refactor(webapi): improve texts and error messages

src/Lobby.ts
=> refactor(src#Lobby): improve texts and error messages

src/TypedConfig.ts
Closes #90
#90 for `TypedConfig` file.
=> refactor(src#TypedConfig): improve texts and error messages

src/discord/OahrDiscord.ts
Addresses remaining inconsistencies in `OahrDiscord.ts` file for #90
=> refactor(discord#OahrDiscord): inconsistencies

src/plugins/MapChecker.ts, src/tests/MapCheckerTest.ts
Addresses remaining inconsistencies in `MapChecker` plugin for #90
Updates strings for `MapCheckerTest`, resolving failing tests.
=> refactor(plugins#MapChecker): inconsistencies

src/webapi/HistoryRepository.ts
Addresses remaining inconsistencies in `HistoryRepository.ts` file for #90
=> refactor(webapi#HistoryRepository): inconsistencies

src/webapi/WebApiClient.ts
Addresses remaining inconsistencies in `WebApiClient.ts` file for #90
=> refactor(webapi#WebApiClient): inconsistencies

src/trials/HistryTrial.ts, src/trials/WebApiTrial.ts
Not needed but it would make the JSON look nice to look at.
=> refactor(trials): JSON format with an indention of 2
